CREATE DATABASE QuanLyBanHang;
USE QuanLyBanHang;
CREATE TABLE Customer 
(
cID		VARCHAR (5) NOT NULL PRIMARY KEY,
cNAME   VARCHAR (20) NOT NULL,
cAGE 	INT 
);
CREATE TABLE Oder
(
oID  	VARCHAR (5) NOT NULL PRIMARY KEY,
cID     VARCHAR (5) NOT NULL,
oDate	DATE,
oTotalPrice INT NOT NULL,
FOREIGN KEY (cID)REFERENCES Customer(cID)
);

CREATE TABLE OrderDetail
(
oID VARCHAR (5) NOT NULL,
pID VARCHAR (5) NOT NULL,
odQTY VARCHAR (5) NOT NULL,
PRIMARY KEY (oID,pID)
);

CREATE TABLE Product 
(
pID VARCHAR (5) NOT NULL PRIMARY KEY,
pNAME VARCHAR (30) NOT NULL,
pPRICE INT (10)
);
